Navbar round2
SachJay/CIS3750_JS pull request #16
Opened 2021-04-08 18:45 UTC by darrenchay

BIG CHUNGUS

2021-04-08 20:09 UTC, mbasak99 commented on client/src/components/utils/Footer/Footer.js
> +      style={{ padding: 20, position: "static", bottom: 0, width: "100vw" }}
This should probably be reverted back to "fixed" cuz 
![image](https://user-images.githubusercontent.com/31177376/114089908-bd105000-9884-11eb-8bb8-e9740720a2a1.png)

2021-04-08 20:25 UTC, mbasak99 commented on client/src/components/utils/Navbar/Navbar.js
> +  console.log(location);
Probably don't need this anymore.

2021-04-08 20:25 UTC, mbasak99 requested changes
Can you fix the places I commented on? Other than that it looks good.

2021-04-08 22:33 UTC, SachJay commented on client/src/Router.js
> +
yah i dont feel like trying to fix it for what it adds

2021-04-09 15:59 UTC, mbasak99 approved these changes

2021-04-09 16:17 UTC, SachJay approved these changes

2021-04-09 16:17 UTC, merged